spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/chiflepop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en la consola (útil para depurar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto específico para MySQL 8 (o versiones modernas)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect